// Generated by CoffeeScript 1.3.3
(function() {
  var app, core, express, port;

  core = require('./blog_core');

  express = require('express');

  app = express.createServer();

  app.use(require('connect-assets')());

  app.use(express["static"](__dirname + '/public'));

  app.set('view engine', 'jade');

  app.get('/', function(req, res) {
    return res.render('blog/index', {
      pageTitle: 'Guilherme Defreitas'
    });
  });

  app.get('/blog/:id', function(req, res) {
    return res.render('blog/show', {
      pageTitle: 'Blog'
    });
  });

  app.get('/sobre', function(req, res) {
    return res.render('contato/index', {
      pageTitle: 'Contato'
    });
  });

  app.get('/aplicativos', function(req, res) {
    return res.render('apps/index', {
      pageTitle: 'Aplicativos'
    });
  });

  port = process.env.port || 3000;

  app.listen(port);

  console.log('Server running at http://0.0.0.0:3000/');

}).call(this);
