exports.dbUrl = 'mongodb://heroku:5bw313@alex.mongohq.com:10085/app5635522'
exports.blog_title = 'Guilherme Defreitas'
exports.blog_description = 'Guilherme Defreitas Blog'
exports.feed_url = 'http://guidefreitas.com/rss.xml'
exports.site_url = 'http://guidefreitas.com'
exports.site_image_url = 'http://guidefreitas.com/icon.png'
exports.site_author = 'Guilherme Defreitas Juraszek'

exports.author_email = 'guilherme.defreitas@gmail.com'
exports.author_facebook_url = 'https://www.facebook.com/guidefreitas'
exports.author_twitter_url = 'http://twitter.com/guidef'
exports.author_linkedin_url = 'http://www.linkedin.com/pub/guilherme-defreitas-juraszek/24/331/2a3'
exports.author_github_url = 'https://github.com/guidefreitas'
exports.author_skype_url = 'callto://guilherme.defreitas'
